### PR TITLE
Update multiple dependencies and bump minimum node version

### PR DESCRIPTION
**Pull request by mayatron**
### Changes

- Update multiple dependencies
- Update minimum node version from `10` to `12`
- Update `ember-try` configuration to add support for Ember LTS 3.28 and use other latest LTS versions
- Update CI configuration for GitHub and Travis (though the latter may not be in use)
- Update `.template-lintrc.js` to extend from `recommended` instead of `octane`

### Notes

This would be a **BREAKING CHANGE** of course, so probably a major version bump would be necessary. Also note that the Ember 4.x scenarios (release, beta, canary) will all fail CI. This should be addressable later within the same new major version.

If there's anything else I can do to help with this, please let me know. If you'd prefer to split this up into smaller PRs or have a different approach in mind, I'm happy to assist if that's useful.

### CODE REVIEW

**Comment by mayatron** [comment]
Will fix lint issues...

**Comment by lifeart** [comment]
looks like it's eslint 8 error, I think it's safe to downgrade it to 7

**Comment by lifeart** [comment]
@mayatron thank you for contribution! I will wait for ember-release CI fixes before major release

**Comment by lifeart** [comment]
published ember-click-outside-modifier@3.0.0

**Pull request merged**
